# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'Artyku\u0142y'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'Tematy'},
        ),
        migrations.AddField(
            model_name='entry',
            name='foto',
            field=models.CharField(default='SOME STRING', max_length=200, verbose_name='foto'),
        ),
    ]
