# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-15 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0002_auto_20200815_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='height',
            field=models.CharField(default='wysoko\u015b\u0107', max_length=200, verbose_name='Wysoko\u015b\u0107 zdj\u0119cie'),
        ),
        migrations.AddField(
            model_name='entry',
            name='width',
            field=models.CharField(default='szeroko\u015b\u0107', max_length=200, verbose_name='Szeroko\u015b\u0107 zdj\u0119cia'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='foto',
            field=models.CharField(default='link do zdj\u0119cia', max_length=200, verbose_name='Zdj\u0119cie'),
        ),
    ]
