# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0004_auto_20200815_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imi\u0119')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail*')),
                ('regulamin_1', models.BooleanField(default=False, verbose_name='Chc\u0119 zapisa\u0107 si\u0119 do newslettera, a co za tym idzie wyra\u017cam zgod\u0119 na otrzymanie na m\xf3j adres e-mail informacji o dzia\u0142alno\u015bci Zanurzeni w zieleni. Zgodnie z ustaw\u0105 o \u015bwiadczeniu us\u0142ug drog\u0105 elektroniczn\u0105 (pole obowi\u0105zkowe)*')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.AlterField(
            model_name='entry',
            name='foto',
            field=models.CharField(default='link do zdj\u0119cia', max_length=200, verbose_name='Zdj\u0119cie'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='height',
            field=models.CharField(default='20%', max_length=200, verbose_name='Wysoko\u015b\u0107 zdj\u0119cie'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='width',
            field=models.CharField(default='100%', max_length=200, verbose_name='Szeroko\u015b\u0107 zdj\u0119cia'),
        ),
    ]
